Release Red03
SeveralCircles/colors pull request #18
Opened 2020-05-18 16:48 UTC by SeveralCircles

This release adds a variety of dumb new features and improves on existing ones. For changes see Files Changed.

Biggest change is addition of Colors Protection, for details on that see #16.

2020-05-18 16:49 UTC, SeveralCircles commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 5
           

Complexity increasing per file
==============================
- src/com/severalcircles/colors/commands/CommandSans.java  2
- src/com/severalcircles/colors/events/ChatEvent.java  2
- src/com/severalcircles/colors/system/protection/BuildExpiry.java  6
- src/com/severalcircles/colors/system/protection/ProtectionCheckFailException.java  2
- src/com/severalcircles/colors/commands/CommandNedry.java  4
- src/com/severalcircles/colors/system/Main.java  6
- src/com/severalcircles/colors/system/protection/RunViaSpigot.java  1
- src/com/severalcircles/colors/commands/CommandPersona.java  1
- src/com/severalcircles/colors/system/protection/ProtectionCheck.java  3
         

Clones added
============
- src/com/severalcircles/colors/system/protection/BuildExpiry.java  1
- src/com/severalcircles/colors/system/Main.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/aidanveney/colors/pullRequest?prid=5544530&bid=18177566)

2020-05-18 16:52 UTC, SeveralCircles commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 5
           

Complexity increasing per file
==============================
- src/com/severalcircles/colors/commands/CommandSans.java  2
- src/com/severalcircles/colors/events/ChatEvent.java  2
- src/com/severalcircles/colors/commands/CommandPersona.java  1
- src/com/severalcircles/colors/system/protection/ProtectionCheck.java  3
- src/com/severalcircles/colors/system/protection/BuildExpiry.java  6
- src/com/severalcircles/colors/system/Main.java  6
- src/com/severalcircles/colors/commands/CommandNedry.java  4
- src/com/severalcircles/colors/system/protection/ProtectionCheckFailException.java  2
- src/com/severalcircles/colors/system/protection/RunViaSpigot.java  1
         

Clones added
============
- src/com/severalcircles/colors/system/protection/BuildExpiry.java  1
- src/com/severalcircles/colors/system/Main.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/aidanveney/colors/pullRequest?prid=5544530&bid=18177566)

2020-05-18 16:54 UTC, Minotaurinmaze requested changes
The "access" command is not properly written on the plugin.yml file. It should include <player> to let people using the command know that they can target specific players.

2020-05-18 16:56 UTC, SeveralCircles commented on src/com/severalcircles/colors/commands/CommandNedry.java
>  package com.severalcircles.colors.commands;
This file could really use some cleaning up. It's a bit of a mess.

2020-05-18 16:56 UTC, SeveralCircles commented on src/com/severalcircles/colors/commands/CommandPersona.java
> +            while (chatspam < 3000) {
We could reduce this number a bit, the messages fly by fast enough that it just doesn't matter.

2020-05-18 16:56 UTC, SeveralCircles commented on src/com/severalcircles/colors/commands/CommandSans.java
> +            target.sendMessage(ChatColor.BLUE + "getttttttttttt dunked on!");
This message doesn't make a lot of sense for sans. Requesting more sans.

2020-05-18 16:59 UTC, SeveralCircles commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 5
           

Complexity increasing per file
==============================
- src/com/severalcircles/colors/system/protection/BuildExpiry.java  6
- src/com/severalcircles/colors/commands/CommandNedry.java  4
- src/com/severalcircles/colors/system/protection/RunViaSpigot.java  1
- src/com/severalcircles/colors/commands/CommandSans.java  2
- src/com/severalcircles/colors/system/protection/ProtectionCheckFailException.java  2
- src/com/severalcircles/colors/commands/CommandPersona.java  1
- src/com/severalcircles/colors/system/Main.java  6
- src/com/severalcircles/colors/events/ChatEvent.java  2
- src/com/severalcircles/colors/system/protection/ProtectionCheck.java  3
         

Clones added
============
- src/com/severalcircles/colors/system/protection/BuildExpiry.java  1
- src/com/severalcircles/colors/system/Main.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/aidanveney/colors/pullRequest?prid=5544530&bid=18177566)

2020-05-19 14:09 UTC, BeegBrainMo requested changes
@Minotaurinmaze Please look at what @SeveralCircles asked you to fix

2020-05-19 16:23 UTC, Minotaurinmaze approved these changes
Everything looks good! I don't see any current issues with it.

2020-05-19 16:31 UTC, SeveralCircles commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- src/com/severalcircles/colors/commands/CommandPersona.java  1
- src/com/severalcircles/colors/commands/CommandSans.java  2
- src/com/severalcircles/colors/system/protection/ProtectionCheckFailException.java  1
- src/com/severalcircles/colors/events/ChatEvent.java  2
- src/com/severalcircles/colors/system/protection/ProtectionCheck.java  3
- src/com/severalcircles/colors/system/protection/BuildExpiry.java  6
- src/com/severalcircles/colors/commands/CommandNedry.java  3
- src/com/severalcircles/colors/system/protection/RunViaSpigot.java  1
- src/com/severalcircles/colors/system/Main.java  6
         

Clones added
============
- src/com/severalcircles/colors/system/protection/BuildExpiry.java  1
- src/com/severalcircles/colors/system/Main.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/aidanveney/colors/pullRequest?prid=5544530&bid=18177566)

2020-05-19 16:32 UTC, Minotaurinmaze approved these changes
I did an uh oh and re-requested review. The code looks good. I don't see anything wrong with it.

2020-05-19 16:32 UTC, BeegBrainMo approved these changes
👌Yes, the changes are very spicy.

2020-05-19 16:32 UTC, SeveralCircles reviewed
All looks good to me!

2020-05-19 16:36 UTC, SeveralCircles commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/com/severalcircles/colors/commands/CommandNedry.java  3
- src/com/severalcircles/colors/events/ChatEvent.java  2
- src/com/severalcircles/colors/commands/CommandSans.java  2
- src/com/severalcircles/colors/system/protection/ProtectionCheck.java  3
- src/com/severalcircles/colors/system/protection/RunViaSpigot.java  1
- src/com/severalcircles/colors/system/Main.java  6
- src/com/severalcircles/colors/system/protection/ProtectionCheckFailException.java  1
- src/com/severalcircles/colors/system/protection/BuildExpiry.java  6
- src/com/severalcircles/colors/commands/CommandPersona.java  1
         

Clones added
============
- src/com/severalcircles/colors/system/Main.java  1
- src/com/severalcircles/colors/system/protection/BuildExpiry.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/aidanveney/colors/pullRequest?prid=5544530&bid=18177566)

2020-05-19 16:37 UTC, merged